markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/css/custom.css

site_name: "EKS Checklist Runbooks"
theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
nav:
  - EKS Checklist: index.md
  - General:
    - 컨테이너 이미지 태그에 latest 미사용 : general/컨테이너_이미지_태그에_latest_미사용.md
  - Security:
    - EKS 클러스터 API 엔드포인트 접근 제어 : security/EKS_클러스터_API_엔드포인트_접근_제어.md
    - IRSA 또는 EKS Pod Identity 기반 권한 부여 : security/IRSA_또는_EKS_Pod_Identity_기반_권한_부여.md
    - 데이터 플레인 노드에 필수로 필요한 IAM 권한만 부여: security/데이터_플레인_노드에_필수로_필요한_IAM_권한만_부여.md
    - 루트 유저가 아닌 유저로 컨테이너 실행: security/루트_유저가_아닌_유저로_컨테이너_실행.md
    - sample3 : security/sample3.md
    - auditlog : security/auditlog.md
    - dataplaneprivate : security/dataplanePrivate.md
  - Scalability:
    - sample2 : scalability/sample2.md
    - karpenter : scalability/karpenter.md 
    - 다양한 인스턴스트 사용 : scalability/various_instance_type.md
  - Stability:
    - sample4 : stability/sample4.md
    - 싱글톤 Pod 미사용 : stability/singletone_pod.md
    - replicasetpod : stability/replicasetpod.md
    - clusterautoscaler : stability/clusterautoscaler.md
    - coreDNSHPA : stability/coredns_hpa.md
    - HorizontalPodAutoscaler : stability/HorizontalPodAutoscaler.md
  - Network:
    - sample1 : network/sample1.md
    - awsLoadBalancerController : network/awsloadbalancercontroller.md
    - subnetipcapacity : network/subnet_ip_capacity.md
    - podreadinessgate : network/podreadinessgate.md
  - Cost:
    - sample5 : cost/sample5.md
    - kubecost : cost/kubecost.md