site_name: "EKS Checklist Runbooks"
theme:
  name: "material"
nav:
  - EKS Checklist: index.md
  - General:
    - 컨테이너 이미지 태그에 latest 미사용 : general/컨테이너_이미지_태그에_latest_미사용.md
  - Security:
    - sample3 : security/sample3.md
    - auditlog : security/auditlog.md
  - Scalability:
    - sample2 : scalability/sample2.md
    - karpenter : scalability/karpenter.md 
  - Stability:
    - sample4 : stability/sample4.md
    - 싱글톤 Pod 미사용 : stability/singletone_pod.md
    - clusterautoscaler : stability/clusterautoscaler.md
    - coreDNSHPA : stability/coreDNSHPA.md
    - HorizontalPodAutoscaler : stability/HorizontalPodAutoscaler.md
  - Network:
    - sample1 : network/sample1.md
  - Cost:
    - sample5 : cost/sample5.md
    - kubecost : cost/kubecost.md