title: "My Runbook"
description: "운영 가이드 문서"
theme: just-the-docs

# 기본 설정
color_scheme: light # or dark
search_enabled: true

# 네비게이션 설정
nav_order: 1
has_children: true

# Sidebar Navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/fitcloud/eks-checklist"

# Collections 설정
collections:
  runbooks:
    output: true
    permalink: /runbooks/:path/

defaults:
  - scope:
      path: ""
      type: "runbooks"
    values:
      layout: default
      nav_order: 2
