name: Build & Upload Release Assets

on:
  release:
    types: [created]

permissions:
  contents: write     # ← 릴리즈 자산 업로드를 위해 반드시 필요

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - id: meta
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then ext=".exe"; else ext=""; fi
          echo "filename=eks-checklist-${GITHUB_REF_NAME}-${{ matrix.os }}-${{ matrix.arch }}$ext" >> $GITHUB_OUTPUT

      - run: |
          mkdir -p dist
          go build -ldflags="-s -w" -o dist/${{ steps.meta.outputs.filename }} ./main.go

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ steps.meta.outputs.filename }}
          asset_name: ${{ steps.meta.outputs.filename }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
