apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-checklist-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-checklist-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "clusterroles", "rolebindings", "clusterrolebindings"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-checklist-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-checklist-role
subjects:
- kind: ServiceAccount
  name: eks-checklist-sa
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eks-checklist-job
spec:
  template:
    spec:
      serviceAccountName: eks-checklist-sa
      containers:
      - name: eks-checklist
        image: public.ecr.aws/x5b3c7k0/eks-checklist:latest
        command: ["/eks-checklist", "--output", "html"]
        volumeMounts:
        - name: output
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: output
        emptyDir: {}
